### ISSUE TITLE
Milestone or remaining issues for v3.3 of aspire budgeting

### ISSUE THREAD

**Issue by kevinjalbert** [aspirebudgetingmobile/aspirebudgeting_ios#129]
👋 I've just started looking into the aspire budgeting system and found out there are mobile applications. I saw a [post on the subreddit](https://www.reddit.com/r/aspirebudgeting/comments/kl11lu/mobile_app_v33/) that indicates that the mobile applications aren't ready for the new version yet.

Is there any tracking issue or milestone that covers what is remaining to get v3.3 working?

**Comment by mohitathwani** [comment]
Hey! Thanks for looking in to the project. Unfortunately there is no issue created yet, I was going to look in to it after I was done with the Add Transaction screen. 

However, I pushed some code last night that will allow you to work on integrating the app with v3.3 of the sheet. 

The idea with 3.3 was to introduce a whole bunch of named ranges so that the apps don't depend on the position of data on the sheet. But I noticed that 3.3 doesn't have all the named ranges and we might have to fall back to the legacy way of fetching data.

**Comment by kevinjalbert** [comment]
> However, I pushed some code last night that will allow you to work on integrating the app with v3.3 of the sheet.

I'm unfortunately not an iOS developer, and my usage would be primarily using it from the app store. I guess at this point it is on the roadmap and the AppStore build eventually will have the 3.3 compatibilities soon?

I'm curious if there is some test flight build, or if some kind of sideloading is a better place to get a working version sooner?

BTW I appreciate the work you've put into this :) I was pleasantly surprised to see an iOS app for this.

**Comment by mohitathwani** [comment]
Here's the TestFlight link: https://testflight.apple.com/join/6Kpe4ue2
